"""ampliar precision de raw_value

Revision ID: 11cc14a3108a
Revises: 8f3785295178
Create Date: 2025-10-31 14:48:52.082687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11cc14a3108a'
down_revision: Union[str, None] = '8f3785295178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('indicator_values', 'raw_value',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               type_=sa.Numeric(precision=30, scale=6),
               existing_nullable=True)
    op.alter_column('indicator_values', 'normalized_value',
               existing_type=sa.NUMERIC(precision=6, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('indicator_values', 'normalized_value',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=6, scale=4),
               existing_nullable=True)
    op.alter_column('indicator_values', 'raw_value',
               existing_type=sa.Numeric(precision=30, scale=6),
               type_=sa.NUMERIC(precision=18, scale=6),
               existing_nullable=True)
    # ### end Alembic commands ###
