"""create countries

Revision ID: 4bc070af79ff
Revises: 2c3210223f63
Create Date: 2025-10-21 19:20:14.391924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc070af79ff'
down_revision: Union[str, None] = '2c3210223f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso2', sa.String(length=2), nullable=False),
    sa.Column('iso3', sa.String(length=3), nullable=False),
    sa.Column('name_es', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_en', name='uq_countries_name_en'),
    sa.UniqueConstraint('name_es', name='uq_countries_name_es')
    )
    op.create_index('idx_countries_names', 'countries', ['name_es', 'name_en'], unique=False)
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_index(op.f('ix_countries_iso2'), 'countries', ['iso2'], unique=True)
    op.create_index(op.f('ix_countries_iso3'), 'countries', ['iso3'], unique=True)
    op.create_index(op.f('ix_countries_name_en'), 'countries', ['name_en'], unique=False)
    op.create_index(op.f('ix_countries_name_es'), 'countries', ['name_es'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_countries_name_es'), table_name='countries')
    op.drop_index(op.f('ix_countries_name_en'), table_name='countries')
    op.drop_index(op.f('ix_countries_iso3'), table_name='countries')
    op.drop_index(op.f('ix_countries_iso2'), table_name='countries')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_index('idx_countries_names', table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
