"""update indicator model to new structure

Revision ID: 4e0ccb875357
Revises: d9ac803fe21b
Create Date: 2025-10-31 02:29:48.009427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e0ccb875357'
down_revision: Union[str, None] = 'd9ac803fe21b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicators', sa.Column('value_type', sa.Enum('IMP', 'DMP', name='indicator_type'), nullable=False))
    op.add_column('indicators', sa.Column('min_value', sa.Numeric(precision=14, scale=4), nullable=True))
    op.add_column('indicators', sa.Column('max_value', sa.Numeric(precision=14, scale=4), nullable=True))
    op.add_column('indicators', sa.Column('justification', sa.String(length=600), nullable=True))
    op.alter_column('indicators', 'unit',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.drop_column('indicators', 'source_summary')
    op.drop_column('indicators', 'min_value_imp')
    op.drop_column('indicators', 'type')
    op.drop_column('indicators', 'max_value_dmp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicators', sa.Column('max_value_dmp', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=True))
    op.add_column('indicators', sa.Column('type', postgresql.ENUM('IMP', 'DMP', name='indicator_type'), autoincrement=False, nullable=False))
    op.add_column('indicators', sa.Column('min_value_imp', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=True))
    op.add_column('indicators', sa.Column('source_summary', sa.VARCHAR(length=600), autoincrement=False, nullable=True))
    op.alter_column('indicators', 'unit',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.drop_column('indicators', 'justification')
    op.drop_column('indicators', 'max_value')
    op.drop_column('indicators', 'min_value')
    op.drop_column('indicators', 'value_type')
    # ### end Alembic commands ###
