"""update indicator max and min

Revision ID: 8f3785295178
Revises: ead38df778c5
Create Date: 2025-10-31 09:20:39.336374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f3785295178'
down_revision: Union[str, None] = 'ead38df778c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('indicators', 'min_value',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Numeric(precision=24, scale=4),
               existing_nullable=True)
    op.alter_column('indicators', 'max_value',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               type_=sa.Numeric(precision=24, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('indicators', 'max_value',
               existing_type=sa.Numeric(precision=24, scale=4),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    op.alter_column('indicators', 'min_value',
               existing_type=sa.Numeric(precision=24, scale=4),
               type_=sa.NUMERIC(precision=14, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
