"""create indicator_values minimal

Revision ID: d9ac803fe21b
Revises: a9b248e9a423
Create Date: 2025-10-22 05:01:15.577717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ac803fe21b'
down_revision: Union[str, None] = 'a9b248e9a423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('normalized_value', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('loaded_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('normalized_value IS NULL OR (normalized_value >= 0 AND normalized_value <= 5)', name='ck_norm_0_5'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.ForeignKeyConstraint(['loaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'indicator_id', name='uq_country_indicator')
    )
    op.create_index('idx_indicator_values_country', 'indicator_values', ['country_id'], unique=False)
    op.create_index('idx_indicator_values_indicator', 'indicator_values', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_indicator_values_id'), 'indicator_values', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicator_values_id'), table_name='indicator_values')
    op.drop_index('idx_indicator_values_indicator', table_name='indicator_values')
    op.drop_index('idx_indicator_values_country', table_name='indicator_values')
    op.drop_table('indicator_values')
    # ### end Alembic commands ###
