"""add public_descriptions table

Revision ID: e9208946abd6
Revises: 1ba8f361ad5b
Create Date: 2025-11-16 06:19:22.268715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9208946abd6'
down_revision: Union[str, None] = '1ba8f361ad5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_public_descriptions_key')
    )
    op.create_index(op.f('ix_public_descriptions_id'), 'public_descriptions', ['id'], unique=False)
    op.create_index(op.f('ix_public_descriptions_key'), 'public_descriptions', ['key'], unique=True)
    op.drop_index('idx_indicator_values_country', table_name='indicator_values')
    op.drop_index('idx_indicator_values_scenario', table_name='indicator_values')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_indicator_values_scenario', 'indicator_values', ['scenario_id'], unique=False)
    op.create_index('idx_indicator_values_country', 'indicator_values', ['country_id'], unique=False)
    op.drop_index(op.f('ix_public_descriptions_key'), table_name='public_descriptions')
    op.drop_index(op.f('ix_public_descriptions_id'), table_name='public_descriptions')
    op.drop_table('public_descriptions')
    # ### end Alembic commands ###
