"""update indicatojustification

Revision ID: ead38df778c5
Revises: 4e0ccb875357
Create Date: 2025-10-31 09:03:47.471735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead38df778c5'
down_revision: Union[str, None] = '4e0ccb875357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('indicators', 'justification',
               existing_type=sa.VARCHAR(length=600),
               type_=sa.String(length=1500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('indicators', 'justification',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=600),
               existing_nullable=True)
    # ### end Alembic commands ###
