"""create scenarios

Revision ID: fdfffaeaf02f
Revises: d4b588be20ba
Create Date: 2025-10-21 21:48:03.022875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdfffaeaf02f'
down_revision: Union[str, None] = 'd4b588be20ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('type', sa.Enum('IMP', 'DMP', name='indicator_type'), nullable=False),
    sa.Column('scale', sa.Enum('FIJA_0_10', 'FIJA_0_100', 'VARIABLE', name='indicator_scale'), nullable=False),
    sa.Column('max_value_dmp', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('min_value_imp', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('source_url', sa.String(length=400), nullable=True),
    sa.Column('source_summary', sa.String(length=600), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_indicators_name'),
    sa.UniqueConstraint('slug', name='uq_indicators_slug')
    )
    op.create_index('idx_indicators_category', 'indicators', ['category_id'], unique=False)
    op.create_index('idx_indicators_name_slug', 'indicators', ['name', 'slug'], unique=False)
    op.create_index(op.f('ix_indicators_id'), 'indicators', ['id'], unique=False)
    op.create_index(op.f('ix_indicators_name'), 'indicators', ['name'], unique=True)
    op.create_index(op.f('ix_indicators_slug'), 'indicators', ['slug'], unique=True)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_scenarios_name')
    )
    op.create_index('idx_scenarios_name_active', 'scenarios', ['name', 'active'], unique=False)
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.create_index(op.f('ix_scenarios_name'), 'scenarios', ['name'], unique=True)
    op.create_table('category_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'category_id', name='uq_scenario_category')
    )
    op.create_table('indicator_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'indicator_id', name='uq_scenario_indicator')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicator_weights')
    op.drop_table('category_weights')
    op.drop_index(op.f('ix_scenarios_name'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_index('idx_scenarios_name_active', table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_indicators_slug'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_name'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_id'), table_name='indicators')
    op.drop_index('idx_indicators_name_slug', table_name='indicators')
    op.drop_index('idx_indicators_category', table_name='indicators')
    op.drop_table('indicators')
    # ### end Alembic commands ###
